CREATE DATABASE COMBUSTIVELBAIXINHA;

USE COMBUSTIVELBAIXINHA;

CREATE TABLE POSTOCOMBUSTIVEL (
ID_COMBUSTIVEL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME TEXT,
VALOR TEXT,
TIPO TEXT,
DATAABASTECIMENTO TEXT
);

SELECT * FROM POSTOCOMBUSTIVEL;