CREATE DATABASE COMBUSTIVELBAIXINHA;

USE COMBUSTIVELBAIXINHA;

CREATE TABLE POSTOCOMBUSTIVEL (
ID_COMBUSTIVEL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME TEXT,
VALOR TEXT,
TIPO TEXT
);

CREATE TABLE USUARIO(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
EMAIL TEXT NOT NULL,
SENHA TEXT NOT NULL,
NOME TEXT NOT NULL
);

DROP TABLE USUARIO;

CREATE TABLE VENDA(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOMECLIENTE TEXT,
DATAVENDA TEXT
);

SELECT * FROM POSTOCOMBUSTIVEL;